### ISSUE TITLE
Why dividing rendered_alpha?

### ISSUE THREAD

**Issue by zcai0612** [BaowenZ/RaDe-GS#12]
https://github.com/BaowenZ/RaDe-GS/blob/4e74c2535a904c8944c751838c6f4761a0f1bd05/train.py#L148

I have a problem understanding this line, Is the rendered depth divided by the rendered alpha (mask)? Is it specially defined?

**Comment by BaowenZ** [comment]
The rendered_depth is the summation of weighted depths, and rendered_mask is the summation of weights. So it is a normalization.

**Comment by zcai0612** [comment]
Got it, and thanks a lot for your response.
