### ISSUE TITLE
Poor training results

### ISSUE THREAD

**Issue by hefan14** [BaowenZ/RaDe-GS#15]
I reproduced the paper and trained it according to the README.md, but the results of 7000 and 30000 iterations were very poor. I used Meshlab to visualize the training results point_cloud.ply. For the training results of scan65 in the DTU dataset, it is almost impossible to see that it is a skull. Could you help me solve this?

**Comment by BaowenZ** [comment]
Wrong glm version will make the training not converge. Please check whether the glm is in the specific version, and whether you use the latest version of our code.

**Comment by hefan14** [comment]
I downloaded the code using the 'git clone' command, which includes glm@5c46b9c and retrained. The training results were the same as before(What I'm referring to is that the point_cloud at 7000 and 30000 steps cannot see the outline of the dataset image. May I ask if this situation occurs during your training). May I ask if my GLM version is correct？
