### ISSUE TITLE
crash when extract mesh

### ISSUE THREAD

**Issue by hlpan** [BaowenZ/RaDe-GS#16]
Thanks for your excellent work.
I'm encountering a segmentation fault when trying to extract a triangle mesh using the `extract_triangle_mesh()` method from the `vbg` module. The script runs fine up until this method is called, at which point the program crashes with the message "Segmentation fault (core dumped)".

**Comment by arvrschool** [comment]
I encountered a similar problem, how did you solve it? Thanks.

**Comment by baizhu0414** [comment]
how do you solve this issue? I meet the same question.

```
> python mesh_extract.py -s input/423tank/ -m output/423tank -r 4

Loaded gaussians from output/423tank/point_cloud/iteration_30000/point_cloud.ply
Reading camera 117/117
cameras extent: 4.158630967140198
段错误 (核心已转储)
```
