### ISSUE TITLE
Question about depth computation

### ISSUE THREAD

**Issue by LinzhouLi** [BaowenZ/RaDe-GS#18]
Hi! Thanks for your great work. 
However I am confused with the depth computation in the CUDA code. The implenmentation seems quite different from the equations introduced in the original paper (Eq.13 - Eq.17). Can you please explain more about the code of function `computeCov2D` in file `diff-gaussian-rasterization/cuda_rasterizar/forward.cu`. Especially Line 165 - Line 168 and Line 180 - Line 184, what is the meaning of `cov_cam_inv`, `uvh`, `uvh_m` and `nJ_inv`?

**Comment by BaowenZ** [comment]
Hi! Thank you for your carefully reading. This is related to #11. `cov_cam_inv` is the Gaussian covariance in camera space, `uvh` is $(u,v,1)$, non-zero components of `nJ_inv` is the first two rows of inverse of `Jn` divided by a factor.

**Comment by LinzhouLi** [comment]
Thanks for your reply!
