### ISSUE TITLE
About equation 22

### ISSUE THREAD

**Issue by AlexRoss-WHS** [BaowenZ/RaDe-GS#19]
Hi,

first of all thank you for this great work! 
Colud you please explain equation 22 ($n = J^T n'$) from the parer to me? 
Why does the transpose of $J$ transform the normal from ray-space to camera-space? I would have expected the inverse of $J$ to be used for this?

**Comment by BaowenZ** [comment]
Hi! Transformation of normal is sightly different from transformation of points. Please refer to http://groups.csail.mit.edu/graphics/classes/6.837/F98/Lecture18/Normals.html

**Comment by AlexRoss-WHS** [comment]
Thank you for the quick response!
