### ISSUE TITLE
Settings Please

### ISSUE THREAD

**Issue by Fanie-Visagie** [BaowenZ/RaDe-GS#20]
Good day,

Really struggling to install...incompatibility errors that goes around in circles...

I am running an RTX 4090...

Installed Cuda 12.1 and with 
>>> import torch
>>> print(torch.__version__)
2.3.1+cu121
>>>

Also had to install visual studio 2019, yet was asked to install the cbuild tools of 2022...

Appreciate if you could advise as to the optimal combination...

**Comment by mbernier-arcturus** [comment]
For building the submodules, you'll need the VS build tools 2022. However, there is an issue with 17.10, so you HAVE TO use 17.9.4.

I also have Cuda 12.1 with python 3.9, for reference. You'll probably have to reboot after installing this.

You might also need to downgrade numpy from 2.0.0 to 1.xx.x (I'm on 1.24.1). There is an incompatibility with the latest NumPy.

**Comment by Fanie-Visagie** [comment]
Mate if you are ever in AUS, I owe you a cold one...THANKS...seems it was the VS Build Tools Version that screwed me...

**Comment by Fanie-Visagie** [comment]
For those needing a link...
![image](https://github.com/BaowenZ/RaDe-GS/assets/107527026/d6a64dbe-330c-42e8-b061-aa653214c53a)

https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history
