### ISSUE TITLE
Questions about performance under large-scale scenes

### ISSUE THREAD

**Issue by DekuLiuTesla** [BaowenZ/RaDe-GS#27]
Thanks for releasing your great work!

I reproduced the paper and get nice results on Tanks and Temples Dataset. However, when I apply RaDeGS on "Building" scene of Mill19 dataset (covering region of hundreds of meters, and lambda_distortion has been set to 1 according to scene scale), it produces poor results compared with vanilla 3DGS.  Several test views looks good, but many others are occluded by planes or have lower fidelity.

<img width="475" alt="performances" src="https://github.com/BaowenZ/RaDe-GS/assets/48622392/143cb0a5-c5f1-49a7-adc9-4a27920b90b5">
<img width="498" alt="qualitative comparison" src="https://github.com/BaowenZ/RaDe-GS/assets/48622392/9d890076-f6b1-4c62-9db7-67fcf13d9d53">

The performance gains a lot when I disable normal and distortion regularization, but performance still lags from vanilla 3DGS.  Is there any insight to generalize RaDeGS better to these large-scale scenes?

**Comment by MELANCHOLY828** [comment]
> 感谢您发布您的出色作品！
> 
> 我复现了这篇论文，并在 Tanks and Temples 数据集上获得了不错的结果。但是，当我将 RaDeGS 应用于 Mill19 数据集的“建筑”场景（覆盖数百米的区域，并且 lambda_distortion 已根据场景比例设置为 1）时，它与 vanilla 3DGS 相比产生了较差的结果。几个测试视图看起来不错，但许多其他视图被平面遮挡或保真度较低。
> 
> <img alt="演出" width="475" src="https://private-user-images.githubusercontent.com/48622392/344051808-143cb0a5-c5f1-49a7-adc9-4a27920b90b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NTU4NzQsIm5iZiI6MTcxOTU1NTU3NCwicGF0aCI6Ii80ODYyMjM5Mi8zNDQwNTE4MDgtMTQzY2IwYTUtYzVmMS00OWE3LWFkYzktNGEyNzkyMGI5MGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA2MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNDhmZGE2ZTQwNTFmZjYxZjk1YjY5ODNiYTJkM2ZiODI1NWQyOTllZGVlNTgxZDRiYmNjNjRlMDNlMzUzYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h114NzZ0Z7Y8EKhv2FCphEIWvvRf5uKw0jl-im9D3pc"> <img alt="定性比较" width="498" src="https://private-user-images.githubusercontent.com/48622392/344052908-9d890076-f6b1-4c62-9db7-67fcf13d9d53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NTU4NzQsIm5iZiI6MTcxOTU1NTU3NCwicGF0aCI6Ii80ODYyMjM5Mi8zNDQwNTI5MDgtOWQ4OTAwNzYtZjZiMS00YzYyLTlkYjctNjdmY2YxM2Q5ZDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA2MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZGQzNTUzNWI4YzdjMjJhYjMxODJhMzg4MjUyNzY3ZDE4ZjYwNjEzMjM4MTUxOThjMWEzYmE1OTljMWYwMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2CQE40BWtSR997eCJJtFNapem0BYuaMQMwAFrNisQPA">
> 当我禁用法线和失真正则化时，性能会大幅提升，但性能仍然落后于原始 3DGS。有没有什么见解可以让 RaDeGS 更好地适用于这些大规模场景？

Can you provide the code for rendering and evaluation?
