### ISSUE TITLE
How to view the depth map?

### ISSUE THREAD

**Issue by forgrabbit** [BaowenZ/RaDe-GS#30]
It feels like an easy question, but I couldn't find any results online. Thank you!
![depth图片](https://github.com/BaowenZ/RaDe-GS/assets/143097274/c4d56272-b827-4c6c-beba-279d9c35618a)

**Comment by BaowenZ** [comment]
Hi! the function [apply_colormap](https://github.com/BaowenZ/RaDe-GS/blob/2d4bc087f1b4bd62c96054fbe89d273490526b81/utils/vis_utils.py#L9) can help visualize depth maps. For example:
```
plt.imshow(apply_depth_colormap(rendered_depth[0,...,None], rendered_mask[0,...,None]).detach().cpu().numpy())
```

**Comment by forgrabbit** [comment]
Thank you for your answer！you helped me a lot！
