### ISSUE TITLE
OOM on vbg.extract_triangle_mesh()

### ISSUE THREAD

**Issue by ThomasWarn** [BaowenZ/RaDe-GS#31]
Good afternoon. I have a medium complexity scene with 120 960x540 images which after running train.py generates a .ply file of approximately 330 MB.

After attempting to process the data into a mesh I receive the following errors. 

> [Open3D INFO] Memory Statistics: (Device) (#Malloc) (#Free)
> [Open3D INFO] ---------------------------------------------
> [Open3D WARNING] CPU:0: 1413 1397 --> 16 with 1176287695 total bytes
> [Open3D WARNING]     0x223be10b040 @ 15786703872 bytes
> [Open3D WARNING]     0x21dbf657040 @ 1482624 bytes
> [Open3D WARNING]     0x21e614f7530 @ 494208 bytes
> [Open3D WARNING]     0x21e6156ffc0 @ 494208 bytes
> [Open3D WARNING]     0x2212ae05040 @ 5529600000 bytes
> [Open3D WARNING]     0x21e11da2040 @ 9600000 bytes
> [Open3D WARNING]     0x21e0376e040 @ 3200000 bytes
> [Open3D WARNING]     0x22274786040 @ 5529600000 bytes
> [Open3D WARNING]     0x21e16bcf040 @ 15416703 bytes
> [Open3D WARNING]     0x21da5622c00 @ 72 bytes
> [Open3D WARNING]     0x21e595b63b0 @ 128 bytes
> [Open3D WARNING]     0x21e61d67010 @ 64932 bytes
> [Open3D WARNING]     0x21e04218040 @ 2283956 bytes
> [Open3D WARNING]     0x21e9d06f040 @ 61666812 bytes
> [Open3D WARNING]     0x21e0db4d040 @ 3200000 bytes
> [Open3D WARNING]     0x21e04455040 @ 2283956 bytes
> [Open3D INFO] ---------------------------------------------

During this code execution, RAM utilization increases to approximately 50 GB out of my 128 GB installed.

After troubleshooting, the error occurs on the line containing `vbg.extract_triangle_mesh()`.

I have attempted to reduce the properties of vbg = o3d.t.geometry.VoxelBlockGrid(), but I continue to get OOM errors.

Any assistance would be appreciated. I was not expecting any OOM issues on the CPU due to my 128 GB of RAM available.

**Comment by BaowenZ** [comment]
Hi! You could try [o3d.pipelines.integration.ScalableTSDFVolume](https://www.open3d.org/docs/release/tutorial/reconstruction_system/integrate_scene.html), which needs much less memory than o3d.t.geometry.VoxelBlockGrid.
