### ISSUE TITLE
About textured

### ISSUE THREAD

**Issue by kingk-boy** [BaowenZ/RaDe-GS#33]
dalao nihao，how can i extract a mesh with textured ?

**Comment by BaowenZ** [comment]
你好! You could replace o3d.t.geometry.VoxelBlockGrid with [o3d.pipelines.integration.ScalableTSDFVolume](https://www.open3d.org/docs/release/tutorial/pipelines/rgbd_integration.html) in [mesh_extract.py](https://github.com/BaowenZ/RaDe-GS/blob/2d4bc087f1b4bd62c96054fbe89d273490526b81/mesh_extract.py#L61). They can be used in the similar way.

**Comment by BaowenZ** [comment]
Hi! We have updated code to extract mesh with texture.

**Comment by kingk-boy** [comment]
Nice !

**Comment by baizhu0414** [comment]
> 你好! You could replace o3d.t.geometry.VoxelBlockGrid with [o3d.pipelines.integration.ScalableTSDFVolume](https://www.open3d.org/docs/release/tutorial/pipelines/rgbd_integration.html) in [mesh_extract.py](https://github.com/BaowenZ/RaDe-GS/blob/2d4bc087f1b4bd62c96054fbe89d273490526b81/mesh_extract.py#L61). They can be used in the similar way.

I have runned mesh_extra and mesh_extract_tetrahedra.py ,but not get mesh with texture. I replace VoxelBlockGrid with [ScalableTSDFVolume] but not get correct result. Can you give me some advice?
![Image](https://github.com/user-attachments/assets/7fb79361-fc5b-462d-9de0-e1ea27631168)
