### ISSUE TITLE
Rasterized Depth Max Value > 1

### ISSUE THREAD

**Issue by shivangi-aneja** [BaowenZ/RaDe-GS#34]
I am trying out the method on custom dataset. The max value of the rendered depth maps > 1 but close to 1 (goes upto 1.4). Do u know why this could be happening?
I've tried to render depth from original 3DGS codebase, it happens there too. I think its important there to figure out this to correctly apply transformations to convert it back to absolute depth.

**Comment by BaowenZ** [comment]
There is not any normalization when rendering depth. So, depth value can be greater than 1.

**Comment by shivangi-aneja** [comment]
Thanks for clarifying :)
