### ISSUE TITLE
Has GOF integration been adapted to RaDe?

### ISSUE THREAD

**Issue by ZachL1** [BaowenZ/RaDe-GS#35]
Thank you for the great work, the performance of RaDe is very impressive!

GOF proposes a method to extract the mesh directly from Gaussian primitives, which can evaluate the opacity of any 3D point. in short, it first [extracts the tetrahedral points](https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/scene/gaussian_model.py#L385) from the Gaussian primitives, then [evaluates the opacity](https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/extract_mesh.py#L17) of these points to obtain the SDF, and then extracts the mesh from the SDF by using marching tetrahedra.

I'm wondering if the ability to evaluate the opacity of an arbitrary 3D point is adapted in RaDe, because I noticed that [`integrate`](https://github.com/BaowenZ/RaDe-GS/blob/main/gaussian_renderer/__init__.py#L94) already exists in the current repository, but I'm not sure if it "integrates opacity based on Rasterizing Depth", and I'm not sure if it's fully functional.

In addition, I have a question about the performance comparison of Tanks & Temples shown in Table 2 of the paper.
1. The pipeline for `GOF` and `Our` to get reconstruction is: render depth -> TSDF to get SDF -> marching cube to get mesh.
2. The result of `GOF#` is supposed to be from the original paper, and the pipeline it uses to get the reconstruction is: extract tetrahedral points -> integrate opacity to get SDF -> marching tetrahedra to get mesh.

So what is the pipeline that `Our#` gets to reconstruct?
Is it based on the first pipeline, replacing the mesh extraction algorithm `marching cube` with `marching tetrahedra`?
Or is it based on the second pipeline, modifying `integrate opacity` to one based on Rasterizing Depth (proposed in this paper)? I think this solution should have better performance.

If it is the second method, I believe you should have a mesh extraction script similar to [GOF](https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/extract_mesh.py), is it possible to put it in this repo? Thank you very much.

**Comment by BaowenZ** [comment]
Hi! I have released the marching tetrahedra. Please reinstall and re-train the RaDe-GS for mesh extraction.

**Comment by ZachL1** [comment]
Thank you very much, this helped me a lot!
