### ISSUE TITLE
Why did you choose to begin reg_kick_on at iter = 15000? Is it related to the desification and pruning of Gaussians?

### ISSUE THREAD

**Issue by LucioSunj** [BaowenZ/RaDe-GS#44]
Thanks for your perfect project! I was confused by this question:

Why did you choose to begin reg_kick_on at iter = 15000? Is it related to the desification and pruning of Gaussians?

Looking for your reply! Thank you very much!

**Comment by BaowenZ** [comment]
Yes, we found that applying densification and regularization at different times resulted in more stable performance, compared to applying them simultaneously.
