### ISSUE TITLE
When using render.py it seems that gaussians' 3d_filter won't be initialised before using them

### ISSUE THREAD

**Issue by LucioSunj** [BaowenZ/RaDe-GS#48]
It seems that When using render.py, gaussians' 3d_filter won't be initialised before using them?

**Comment by BaowenZ** [comment]
Sorry, I cannot reproduce this error. Did this [line](https://github.com/BaowenZ/RaDe-GS/blob/81de6b520cf570bc99a514dac1bdb59541eb7f17/scene/gaussian_model.py#L557) work when using render.py?
