### ISSUE TITLE
Training parameters for "modifications"

### ISSUE THREAD

**Issue by hiyyg** [BaowenZ/RaDe-GS#52]
Hi! 

In the readme, you said that the parameters such as the distortion loss weight have been changed. However, it seems the default argument values are still kept. Is it safe to remove them?

**Comment by zhanghaoyu816** [comment]
> Hi! I removed the distortion loss, so the corresponding parameters can be removed. And I'll clean the code for clarity.

Hello, I want to know why you decide to remove the depth distortion loss?
